#!/bin/bash

## Config synchronisation script
#  =============================
#  LEAF syncConf

source syncConf.include

## SET BASE DIR
BASE_DIR="$HOME"

## SET OBJECTS
OBJECT[0]=.vimrc
OBJECT[1]=.vim/


# Echo commands instead of executing them if DRY is set to true
# DRY=TRUE


## RUN SCRIPT
main_leaf $*

