#!/bin/bash

## Config synchronisation script
#  =============================
#  LEAF syncConf

source syncConf.include

## SET BASE DIR
BASE_DIR="$HOME/scripts"

## SET OBJECTS
OBJECT[0]=ssh-agent.sh
OBJECT[1]=switch.sh


# Echo commands instead of executing them if DRY is set to true
# DRY=TRUE


## RUN SCRIPT
main_leaf $*

